language: node_js
node_js: '12'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
script:
  - npm run build:demo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: demo
  verbose: true
  on:
    branch: master
